The nav menu follow the scroll, repair nav menu's media
paxo-phone/paxo-site pull request #53
Opened 2023-12-15 14:04 UTC by HeyHeyChicken

Bonjour,

Cette MR résous les soucis suivant :
- Le menu de navigation ne suis pas au scroll.
- Le responsive du menu de navigation n'est pas très bien réglé, il se casse la goule au milieu.

2023-12-17 10:14 UTC, DarkBrines requested changes
- ![image](https://github.com/paxo-phone/paxo-site/assets/94066559/8dcf9cc8-be77-4682-8f4d-590f2a5c3687) Le header prend trop de place sur les petits écrans au scroll, aussi l'arrière plan du lang-select est trop foncé après le scroll.

- ![image](https://github.com/paxo-phone/paxo-site/assets/94066559/e0e9e1f1-214d-4453-b7aa-b90c67f32e37) Le header aussi trop grand en écran vertical

- ![image](https://github.com/paxo-phone/paxo-site/assets/94066559/057da439-0b47-4aba-8590-0b84f0c5b77b) Le selecteur des langues en écran vertical semble aussi avoir un bug visuel.

Outre ses problèmes mineurs, le code est très propre et j'aime beaucoup l'idée de changement du header au scroll. Merci pour avoir résolu le problème du scroll sur écran vertical, on s'en sortait pas !

2023-12-17 10:14 UTC, DarkBrines commented on resources/js/main.js
> +});
Execution d'un code au scroll ne semble pas très optimisé. Se pencher sur une alternative CSS.

2023-12-17 20:27 UTC, HeyHeyChicken commented
![image](https://github.com/paxo-phone/paxo-site/assets/33424294/efe780e8-4859-4bc4-bf5d-c57f1c8d9197)
C'est fait, le header est rétréci au scroll.

2023-12-20 14:33 UTC, DarkBrines approved these changes

2023-12-20 14:37 UTC, DarkBrines commented
Aussi, peut-être changer l'arrière-plan du header plutot que de mettre un bordure

2023-12-22 10:13 UTC, HeyHeyChicken commented
@DarkBrines
C'est quelque chose comme cela que vous souhaitez ?
![image](https://github.com/paxo-phone/paxo-site/assets/33424294/3b80772d-d2b7-44dc-8dae-de9279cda15b)
Je suis pas super fan, mais pk pas.

2023-12-22 17:19 UTC, DarkBrines commented
Ca m'a l'air pas mal du tout

2023-12-22 17:20 UTC, DarkBrines commented
@RaphaelGoutmann @paxo-rch un avis ?

2023-12-22 17:47 UTC, SuperMaxhou commented
Je trouve que la couleur verte du header est un peu trop pétante

2023-12-29 14:19 UTC, merged